title:        Puppet Lunch
tagline:      ""
url:          http://puppetlunch.com
author:
  name:       "S. Young"
  email:      "simon@puppetlunch.com"
markdown:     kramdown
permalink:    none
highlighter:  rouge
paginate:     5
baseurl:      ""
